### PR TITLE
basic support of ctrl_ln1 & ctrl_ln2 tested on gateway firewire 1.4.1_146.0141

### PR DESCRIPTION
**Pull request by januslo**
#69 #76 #52   basic support of ctrl_ln1 & ctrl_ln2 basic support of ctrl_ln1 & ctrl_ln2 tested on gateway firewire 1.4.1_146.0141

### CODE REVIEW

**Comment by happylichuanxi** [comment]
It works,thanks for sharing!

**Comment by theo-69** [comment]
@snOOrz please merge, need the neutral-live wire support

**Comment by theo-69** [comment]
@januslo hey quick question what file do i have to change in order to get this working

**Comment by TTDARK** [comment]
These lines are currently in my lib/AqaraPlatform.js . But Homekit still only shows status of my dual light switch (with neutral wire). Turning on/off doesn't control the device. Does anyone have a solution? 
Gateway Firmware v. 1.4.1_148.0143

    'sensor_ht' : new TemperatureAndHumidityParser(this),
    'motion' : new MotionParser(this),
    'magnet' : new ContactParser(this),
    'ctrl_neutral1' : new LightSwitchParser(this),
    'ctrl_neutral2' : new DuplexLightSwitchParser(this),
    'ctrl_ln1' : new LightSwitchParser(this),
    'ctrl_ln2' : new DuplexLightSwitchParser(this),
    '86sw1' : new EightySixSwitchParser(this),
    '86sw2' : new DuplexEightySixSwitchParser(this),
    'plug' : new PlugSwitchParser(this)`

**Pull request merged**
