### PR TITLE
adding new features, include gateway light and light sensor

### PR DESCRIPTION
**Pull request by crhan**
- 终于实现了小米网关的亮度控制
- 新增小米网关的亮度传感器数据
- 显式的注册 Gateway 组件
- 重构, 抽出部分函数以复用
- 重构, 分离出 Commander.js
- 打开 debug 日志

---

I'm so sorry I've wrote this PR in Chinese, because that is more nature for me and I know that the repo's author is a Chinese. It's pretty funny to found that xiaomi (aqara for the smart home brand?) has sold it's product to that many countries and you guys are also interested in it.

Back to this PR, I've taken a big code refactor to the project, so this PR may not be acceptable to the author. So if you think the feature is great, you are welcome to use my fork and branch here: https://github.com/crhan/homebridge-aqara/tree/ruohan.chen/add_xiaomi_gateway

### CODE REVIEW

**Comment by crhan** [comment]
- 网关灯色彩功能尚未实现，还在摸索中
- 重构了一些代码。。。希望作者大人不要打我

**Review by czdeee — COMMENTED** [review]
哥们可以

**Comment by crhan** [comment]
Fixing a switch commander problem, wait a moment.

**Comment by crhan** [comment]
fixed, please review and pull this request

**Comment by a900927** [comment]
开启网关灯时会报未知错误
[4/24/2017, 12:34:13 AM] characteristic not found: function () {
  Characteristic.call(this, 'Hue', '00000013-0000-1000-8000-0026BB765291');
  this.setProps({
    format: Characteristic.Formats.FLOAT,
    unit: Characteristic.Units.ARC_DEGREE,
    maxValue: 360,
    minValue: 0,
    minStep: 1,
    perms: [Characteristic.Perms.READ, Characteristic.Perms.WRITE, Characteristic.Perms.NOTIFY]
  });
  this.value = this.getDefaultValue();
}
不过可以用

**Comment by crhan** [comment]
@a900927 你说的是对的，关闭 Hue commander 的时候不小心引入了一个 bug

**Comment by qdwhltop** [comment]
可以哥们，我是啥也看不懂。谢谢你们的努力！~

**Comment by a900927** [comment]
我更新到你最新的代码。但是还是会有之前那个错误。
还有我想问一下。在“家庭”app的数据多久会发心跳包更新？每次都要执行操作，数据才会更新

**Comment by crhan** [comment]
@a900927 这个问题解释起来比较复杂，根源是 gateway 注册进 homebridge 的时候没有加上 HUE 的 characteristic。导致 homebridge 的 cache 中没有这个属性，还原出来的时候就会找不到。解决方法有两个：

1. 在代码里面 tricky 的先 unregister 一下 gateway，然后再等他下次注册
2. 找到 `~/.homebridge/accessories/cachedAccessories` 中的 gateway，删掉再启动 homebridge，让他重新注册一下

**Comment by a900927** [comment]
@crhan 原来如此。第一种方法不太懂啊。第二种我回去试试 :)

**Comment by FSZJ** [comment]
为何修改完AqaraPlatform.js   AqaraAccessoryFactory.js  启动homebridge 报错

**Comment by crhan** [comment]
@FSZJ 是我这个分支？报错的内容是啥？

**Comment by FSZJ** [comment]
@crhan 

/usr/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

Error: The module '/usr/lib/node_modules/homebridge/node_modules/mdns/build/Release/dns_sd_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

**Comment by crhan** [comment]
不是我修改的问题，mdns 的问题你要自己想想办法查查看

**Comment by byuan04** [comment]
请问下我已经添加了  "fakeLightBulbForLightSwitch": true

并且删除了 persist 及 accessories 目录, 怎么还是看不到网关自带的LED

**Comment by Stevenyu1982** [comment]
支持一下，牛逼

**Comment by a900927** [comment]
@byuan04 要更新成他的代码。fakeLightBulbForLightSwitch应该指的是可以使用网关上的按钮开关灯。不是指可以用手机控制灯

**Comment by crhan** [comment]
@snOOrz 作者大大看这个可以合么。。？其实我这段时间已经转战 HA 了。。。。。这边不会再更新了

**Comment by fxdpz** [comment]
@crhan 启动时报错，信息如下：
May 09 13:47:10 rpb1 homebridge[8971]: /usr/local/lib/node_modules/homebridge-aqara/lib/AqaraPlatform.js:314
May 09 13:47:10 rpb1 homebridge[8971]: commander = new commander.LightSwitchCommander(this.platform, deviceSid, report['model'], 'channel_0');
May 09 13:47:10 rpb1 homebridge[8971]: ^
May 09 13:47:10 rpb1 homebridge[8971]: TypeError: Cannot read property 'LightSwitchCommander' of undefined
May 09 13:47:10 rpb1 homebridge[8971]: at LightSwitchParser.parse (/usr/local/lib/node_modules/homebridge-aqara/lib/AqaraPlatform.js:314:32)
May 09 13:47:10 rpb1 homebridge[8971]: at AqaraPlatform.parseMessage (/usr/local/lib/node_modules/homebridge-aqara/lib/AqaraPlatform.js:209:27)
May 09 13:47:10 rpb1 homebridge[8971]: at emitTwo (events.js:106:13)
May 09 13:47:10 rpb1 homebridge[8971]: at Socket.emit (events.js:191:7)
May 09 13:47:10 rpb1 homebridge[8971]: at UDP.onMessage (dgram.js:549:8)

**Comment by crhan** [comment]
@fxdpz use the latest code and try again

**Comment by WangZhuo2015** [comment]
There's an error in 'AqaraAccessoryFactory.js'
In this line:
`const commander = require('./Commander');`
missing an character  's'，node throws Error---`Error: Cannot find module './Commander'`
It should be:
`const commander = require('./Commanders');`

**Comment by crhan** [comment]
Thank you all and I'm not going to maintain this code any further. So just close this PR

**Pull request closed without merging**
